services:
  # Backend API Service
  - type: web
    name: refugee-learning-backend
    runtime: node
    plan: starter
    buildCommand: cd backend && npm ci
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_TYPE
        value: pg
      # Use external free database service
      # Set these in Render dashboard or use a free service like Supabase
      - key: DATABASE_URL
        value: # Set this to your external database URL (e.g., Supabase, Railway, etc.)
      - key: JWT_SECRET
        generateValue: true
    autoDeploy: false

  # Dashboard Frontend Service  
  - type: static
    name: refugee-learning-dashboard
    buildCommand: cd dashboard && npm ci && npm run build
    publishPath: dashboard/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://refugee-learning-backend.onrender.com/api
    autoDeploy: false

# Database - Using external free database service
# For completely free setup, consider using:
# - Railway PostgreSQL (free tier)
# - Supabase (free tier)
# - PlanetScale (free tier)
# - or SQLite for development
# databases:
#   - name: refugee-learning-db
#     databaseName: refugee_learning_platform
#     plan: free  # Note: Render's free database has limitations
